##--------------------------------------------------
##           __     _             _         
##      ____/ /__  (_)___  _   __(_)___ ___ 
##     / __  / _ \/ / __ \| | / / / __ `__ \
##    / /_/ /  __/ / / / /| |/ / / / / / / /
##    \__,_/\___/_/_/ /_(_)___/_/_/ /_/ /_/ 
##                                          
##--------------------------------------------------

##--------------------------------------------------
## Base
##--------------------------------------------------
[[plugins]]
repo= 'Shougo/dein.vim'


##--------------------------------------------------
## Editor
##--------------------------------------------------
[[plugins]]
repo = 'scrooloose/syntastic'

#[[plugins]]
#repo = 'bronson/vim-trailing-whitespace'

# [[plugins]]
# repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
map <Leader>s <Plug>(operator-surround-append)
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
map mj <Plug>(easy_motion-bd-w)
nmap mj <Plug>(easymotion-overwin-w)
map ml <Plug>(easymotion-bd-jk)
nmap ml <Plug>(easymotion-overwin-line)
map mk <Plug>(easymotion-bd-f)
nmap mk <Plug>(easymotion-verwin-f)
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
map <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'violetyk/iikanji-markdown.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'fatih/vim-go'

##--------------------------------------------------
## Auto Complate
##--------------------------------------------------
#[[plugins]]
#repo = 'Shougo/ddc.vim'
#depends = 'denops.vim'

#[[plugins]]
#repo = 'Shougo/ddc-around'

#[[plugins]]
#repo = 'Shougo/ddc-sorter_rank'

#[[plugins]]
#repo = 'Shougo/ddc-matcher_head'

#[[plugins]]
#repo = 'high-moctane/nextword'

#[[plugins]]
#repo = 'high-moctane/nextword-data'

#[[plugins]]
#repo = 'Shougo/ddc-nextword'

#[[plugins]]
#repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'keremc/asyncomplete-clang.vim'

##--------------------------------------------------
## ddu plugins
##--------------------------------------------------
#[[plugins]]
#repo = 'Shougo/ddu.vim'
#hook_add = '''
#call ddu#custom#patch_global({'ui': 'ff'})
#call ddu#custom#patch_global({'kindOptions': {'file': {'defaultAction': 'open',},}})
#call ddu#custom#patch_global({'sourceOptions': {'_': {'matchers': ['matcher_substring'],},}})
#'''

#[[plugins]]
#repo = 'Shougo/ddu-ui-ff'

##--------------------------------------------------
## Formatter
##--------------------------------------------------
[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'

##--------------------------------------------------
## Language
##--------------------------------------------------
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown']
'''

##--------------------------------------------------
## Status line
##--------------------------------------------------
[[plugins]]
repo = 'itchyny/lightline.vim'

##--------------------------------------------------
## Finder
##--------------------------------------------------
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'

##--------------------------------------------------
## Color Theme 
##--------------------------------------------------
[[plugins]]
repo = "sonph/onehalf"

##--------------------------------------------------
## Utilities
##--------------------------------------------------
[[plugins]]
repo = 'junegunn/goyo.vim' # Enable Zen mode

[[plugins]]
repo = 'vim-denops/denops.vim' # Deno Base Plugin
hook_add = '''
set runtimepath^=~/Denops/_develop
" let g:denops#debug = 1
'''

[[plugins]]
repo = 'itchyny/calendar.vim' # Enable calendar view
hook_add = '''
let g:calendar_first_day = "monday"
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
nmap <Leader>t <Plug>(openbrowser-smart-earch)
vmap <Leader>t <Plug>(openbrowser-smart-earch)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'LeafCage/vimhelpgenerator' # Help Generator
